"use client";

// import type { Metadata } from "next";
import TabBar from "@/components/TabBar/page";
import { useEffect, useState } from "react";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isNative, setIsNative] = useState(false);

  useEffect(() => {
    window.addEventListener("message", (event) => {
      if (event.data === "native") {
        setIsNative(true);
      }
    });
  }, [isNative]);

  if (isNative) return null; // 네이티브일 때는 탭바를 렌더링하지 않음

  return (
    <html lang="en">
      <body>
        {children}
        {!isNative && <TabBar />}
      </body>
    </html>
  );
}
